name: Build Plugin and Upload Release

on:
  push:
    branches:
      - master # Build wird bei jeder Änderung im `master`-Branch ausgelöst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code aus deinem Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 23 SDK
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Alternativen: adopt, zulu, usw.
          java-version: '23'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Extract name and version from pom.xml
      - name: Extract Maven Project Info
        id: get_project_info
        run: |
          project_name=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project Name: $project_name"
          echo "Version: $version"
          echo "project_name=$project_name" >> $GITHUB_ENV
          echo "release_version=$version" >> $GITHUB_ENV

      # Build the plugin using Maven
      - name: Build with Maven
        run: mvn clean package

      # Create a GitHub Release
      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v${{ env.release_version }} # Setzt die Version als GitHub Tag
          release_name: ${{ env.project_name }} v${{ env.release_version }} # Name und Version aus der pom.xml
          draft: false
          prerelease: false

      # Upload JAR to Release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar # Der Pfad zu deinem gebauten Artefakt
          asset_name: ${{ env.project_name }}-${{ env.release_version }}.jar # Name der JAR-Datei
          asset_content_type: application/java-archive